gh-369 Optional bootstrapping of Web Server's local Maven repo

diff --git a/deployment/aws/core/cloudformation/gaffer-web.yaml b/deployment/aws/core/cloudformation/gaffer-web.yaml
--- a/deployment/aws/core/cloudformation/gaffer-web.yaml
+++ b/deployment/aws/core/cloudformation/gaffer-web.yaml
@@ -109,6 +109,7 @@ Metadata:
           default: Web Server Config
         Parameters:
           - InstanceType
+          - VpcId
           - SubnetId
           - ExtraSecurityGroups
           - KeyName
@@ -191,14 +192,13 @@ Mappings:
 
 Conditions:
 
-    SchemaStoredInS3: !Not [!Equals [!Ref GafferSchemaJarS3Url, ""]]
+  SchemaStoredInS3: !Not [!Equals [!Ref GafferSchemaJarS3Url, ""]]
+  BootstrapLocalMavenRepo: !Not [!Equals [!Ref MavenRepoTarball, ""]]
 
 Resources:
 
   WebServer:
     Type: AWS::EC2::Instance
-    # We really need the following line, but CloudFormation doesn't currently support it :(
-    #DependsOn: !If [SchemaStoredInS3, "WebServerS3SchemaAccessPolicy", !Ref "AWS::NoValue"]
     Properties:
       ImageId: !FindInMap [InstanceAmi, Ref: "AWS::Region", 64ebs]
       InstanceType: !Ref InstanceType
@@ -217,170 +217,173 @@ Resources:
           Value: !Join ["-", [Ref: "AWS::StackName", "web"]]
       UserData:
         Fn::Base64:
-          !Sub |
-            #!/bin/bash -xe
+          !Sub
+            - |
+              #!/bin/bash -xe
 
-            WAIT_HANDLE_URL="${WebServerReadyHandler}"
-            if [[ "$WAIT_HANDLE_URL" ]]; then
-              function awsSignal {
-                /opt/aws/bin/cfn-signal -e $? "$WAIT_HANDLE_URL"
-              }
-              trap awsSignal EXIT
-            fi
-
-            GAFFER_VERSION="${GafferVersion}"
-            GAFFER_TOOLS_VERSION="${GafferToolsVersion}"
-
-            MAVEN_VERSION=3.5.0
-            MAVEN_DOWNLOAD_URL=https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
-
-            # Upgrade Java and install Tomcat
-            yum remove -y java-1.7.0-openjdk
-            yum install -y java-1.8.0-openjdk-devel tomcat7 tomcat7-admin-webapps
-
-            /etc/init.d/tomcat7 stop
-
-            tee -a /etc/tomcat7/tomcat7.conf <<EOF
-            CATALINA_OPTS="-Djava.net.preferIPv4Stack=true"
-            EOF
-
-            function install_dev_tools {
-              # Install Apache Maven
-              if ! which mvn >/dev/null 2>&1; then
-                echo "Downloading Apache Maven $MAVEN_VERSION from $MAVEN_DOWNLOAD_URL"
-                curl -fLO $MAVEN_DOWNLOAD_URL
-                tar -xf apache-maven-$MAVEN_VERSION-bin.tar.gz
-                rm -f apache-maven-$MAVEN_VERSION-bin.tar.gz
-                export PATH=$PWD/apache-maven-$MAVEN_VERSION/bin:$PATH
+              WAIT_HANDLE_URL="${WebServerReadyHandler}"
+              if [[ "$WAIT_HANDLE_URL" ]]; then
+                function awsSignal {
+                  /opt/aws/bin/cfn-signal -e $? "$WAIT_HANDLE_URL"
+                }
+                trap awsSignal EXIT
               fi
-            }
 
-            if [ "${MavenRepoTarball}" != "" ]; then
-              # Bootstrapping the local Maven repo is allowed to fail, we will just fallback to downloading all the
-              # dependencies from Maven Central...
-              set +e
-              pushd $HOME
-              aws s3 cp s3://${MavenRepoTarball} maven-repo.tar.gz
-              tar -xf maven-repo.tar.gz
-              rm -f maven-repo.tar.gz
-              popd
-              set -e
-            fi
+              GAFFER_VERSION="${GafferVersion}"
+              GAFFER_TOOLS_VERSION="${GafferToolsVersion}"
 
-            # Need to work out if we can download the Gaffer accumulo-rest.war or if we need to build it from source...
-            if ! curl -fL -o rest.war https://repo1.maven.org/maven2/uk/gov/gchq/gaffer/accumulo-rest/$GAFFER_VERSION/accumulo-rest-$GAFFER_VERSION.war; then
-              echo "Building Gaffer accumulo-rest.war from branch $GAFFER_VERSION..."
-              install_dev_tools
+              MAVEN_VERSION=3.5.0
+              MAVEN_DOWNLOAD_URL=https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
 
-              curl -fLO https://github.com/gchq/Gaffer/archive/$GAFFER_VERSION.zip
-              unzip $GAFFER_VERSION.zip
-              rm $GAFFER_VERSION.zip
-              cd Gaffer-$GAFFER_VERSION
+              # Upgrade Java and install Tomcat
+              yum remove -y java-1.7.0-openjdk
+              yum install -y java-1.8.0-openjdk-devel tomcat7 tomcat7-admin-webapps
 
-              mvn clean package -Pquick -pl rest-api/accumulo-rest --also-make
+              /etc/init.d/tomcat7 stop
 
-              GAFFER_POM_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)
-              echo "Detected Gaffer version as $GAFFER_POM_VERSION"
+              tee -a /etc/tomcat7/tomcat7.conf <<EOF
+              CATALINA_OPTS="-Djava.net.preferIPv4Stack=true"
+              EOF
 
-              cp rest-api/accumulo-rest/target/accumulo-rest-$GAFFER_POM_VERSION.war /var/lib/tomcat7/webapps/rest.war
+              function install_dev_tools {
+                # Install Apache Maven
+                if ! which mvn >/dev/null 2>&1; then
+                  echo "Downloading Apache Maven $MAVEN_VERSION from $MAVEN_DOWNLOAD_URL"
+                  curl -fLO $MAVEN_DOWNLOAD_URL
+                  tar -xf apache-maven-$MAVEN_VERSION-bin.tar.gz
+                  rm -f apache-maven-$MAVEN_VERSION-bin.tar.gz
+                  export PATH=$PWD/apache-maven-$MAVEN_VERSION/bin:$PATH
+                fi
+              }
 
-              cd ..
-              rm -rf Gaffer-$GAFFER_VERSION
-            else
-              echo "Using Gaffer accumulo-rest.war from Maven Central..."
-              mv rest.war /var/lib/tomcat7/webapps/
-              GAFFER_POM_VERSION=$GAFFER_VERSION
-            fi
+              cd /root
+              if [ "${MavenRepoTarball}" != "" ]; then
+                # Bootstrapping the local Maven repo is allowed to fail, we will just fallback to downloading all the
+                # dependencies from Maven Central...
+                set +e
+                aws s3 cp s3://${MavenRepoTarball} maven-repo.tar.gz
+                tar -xf maven-repo.tar.gz
+                rm -f maven-repo.tar.gz
+                set -e
+              fi
 
-            # Need to work out if we can download the Gaffer UI or if we need to build it from source...
-            if ! curl -fL -o ui.war https://repo1.maven.org/maven2/uk/gov/gchq/gaffer/ui/$GAFFER_TOOLS_VERSION/ui-$GAFFER_TOOLS_VERSION.war; then
-              echo "Building the Gaffer UI from branch $GAFFER_TOOLS_VERSION..."
-              install_dev_tools
+              # Need to work out if we can download the Gaffer accumulo-rest.war or if we need to build it from source...
+              if ! curl -fL -o rest.war https://repo1.maven.org/maven2/uk/gov/gchq/gaffer/accumulo-rest/$GAFFER_VERSION/accumulo-rest-$GAFFER_VERSION.war; then
+                echo "Building Gaffer accumulo-rest.war from branch $GAFFER_VERSION..."
+                install_dev_tools
 
-              curl -fLO https://github.com/gchq/gaffer-tools/archive/$GAFFER_TOOLS_VERSION.zip
-              unzip $GAFFER_TOOLS_VERSION.zip
-              rm $GAFFER_TOOLS_VERSION.zip
-              cd gaffer-tools-$GAFFER_TOOLS_VERSION
+                curl -fLO https://github.com/gchq/Gaffer/archive/$GAFFER_VERSION.zip
+                unzip $GAFFER_VERSION.zip
+                rm $GAFFER_VERSION.zip
+                cd Gaffer-$GAFFER_VERSION
 
-              mvn clean package -Pquick -pl ui --also-make
+                mvn clean package -Pquick -pl rest-api/accumulo-rest --also-make
 
-              GAFFER_TOOLS_POM_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)
-              echo "Detected Gaffer Tools version as $GAFFER_TOOLS_POM_VERSION"
+                GAFFER_POM_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)
+                echo "Detected Gaffer version as $GAFFER_POM_VERSION"
 
-              cp ui/target/ui-$GAFFER_TOOLS_POM_VERSION.war /var/lib/tomcat7/webapps/ui.war
+                cp rest-api/accumulo-rest/target/accumulo-rest-$GAFFER_POM_VERSION.war /var/lib/tomcat7/webapps/rest.war
 
-              cd ..
-              rm -rf gaffer-tools-$GAFFER_TOOLS_VERSION
-            else
-              echo "Using Gaffer UI from Maven Central..."
-              mv ui.war /var/lib/tomcat7/webapps/
-            fi
+                cd ..
+                rm -rf Gaffer-$GAFFER_VERSION
+              else
+                echo "Using Gaffer accumulo-rest.war from Maven Central..."
+                mv rest.war /var/lib/tomcat7/webapps/
+                GAFFER_POM_VERSION=$GAFFER_VERSION
+              fi
 
-            # Grab the Accumulo password from an SSM Parameter
-            ENCRYPTED_PASSWORD=$(aws ssm get-parameters --names "${PasswordParameter}" --region "${AWS::Region}" --output text --query Parameters[0].Value)
-            if [ "$ENCRYPTED_PASSWORD" == "" ]; then
-              echo "Unable to retrieve Gaffer password from AWS SSM Parameter: ${PasswordParameter}"
-              exit 1
-            fi
+              # Need to work out if we can download the Gaffer UI or if we need to build it from source...
+              if ! curl -fL -o ui.war https://repo1.maven.org/maven2/uk/gov/gchq/gaffer/ui/$GAFFER_TOOLS_VERSION/ui-$GAFFER_TOOLS_VERSION.war; then
+                echo "Building the Gaffer UI from branch $GAFFER_TOOLS_VERSION..."
+                install_dev_tools
 
-            # Decrypt the Accumulo password
-            PASSWORD=$(aws kms decrypt --region "${AWS::Region}" --ciphertext-blob fileb://<(echo "$ENCRYPTED_PASSWORD" | base64 -d) --query Plaintext --output text | base64 -d)
-            if [ "$PASSWORD" == "" ]; then
-              echo "Unable to decrypt Gaffer password!"
-              exit 2
-            fi
+                curl -fLO https://github.com/gchq/gaffer-tools/archive/$GAFFER_TOOLS_VERSION.zip
+                unzip $GAFFER_TOOLS_VERSION.zip
+                rm $GAFFER_TOOLS_VERSION.zip
+                cd gaffer-tools-$GAFFER_TOOLS_VERSION
 
-            # Create Gaffer configuration
-            GAFFER_CONF_DIR=/opt/gaffer
+                mvn clean package -Pquick -pl ui --also-make
 
-            mkdir -p $GAFFER_CONF_DIR/etc
-            mkdir -p $GAFFER_CONF_DIR/schemas
+                GAFFER_TOOLS_POM_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)
+                echo "Detected Gaffer Tools version as $GAFFER_TOOLS_POM_VERSION"
 
-            tee -a $GAFFER_CONF_DIR/etc/graphConfig.json <<EOF
-            {
-              "graphId": "${GraphId}"
-            }
-            EOF
+                cp ui/target/ui-$GAFFER_TOOLS_POM_VERSION.war /var/lib/tomcat7/webapps/ui.war
 
-            tee -a $GAFFER_CONF_DIR/etc/store.properties <<EOF
-            gaffer.store.class=uk.gov.gchq.gaffer.accumulostore.AccumuloStore
-            gaffer.store.properties.class=uk.gov.gchq.gaffer.accumulostore.AccumuloProperties
-            accumulo.instance=${AccumuloInstanceName}
-            accumulo.zookeepers=${GafferEmrMasterDNS}
-            accumulo.table=${GraphId}
-            accumulo.user=${UserName}
-            accumulo.password=$PASSWORD
-            EOF
+                cd ..
+                rm -rf gaffer-tools-$GAFFER_TOOLS_VERSION
+              else
+                echo "Using Gaffer UI from Maven Central..."
+                mv ui.war /var/lib/tomcat7/webapps/
+              fi
 
-            # Point Tomcat at Gaffer config
-            tee -a /etc/tomcat7/tomcat7.conf <<EOF
-            CATALINA_OPTS="-Dgaffer.rest-api.basePath=rest \$CATALINA_OPTS"
-            CATALINA_OPTS="-Dgaffer.graph.config=$GAFFER_CONF_DIR/etc/graphConfig.json \$CATALINA_OPTS"
-            CATALINA_OPTS="-Dgaffer.schemas=$GAFFER_CONF_DIR/schemas \$CATALINA_OPTS"
-            CATALINA_OPTS="-Dgaffer.storeProperties=$GAFFER_CONF_DIR/etc/store.properties \$CATALINA_OPTS"
-            EOF
+              # Grab the Accumulo password from an SSM Parameter
+              ENCRYPTED_PASSWORD=$(aws ssm get-parameters --names "${PasswordParameter}" --region "${AWS::Region}" --output text --query Parameters[0].Value)
+              if [ "$ENCRYPTED_PASSWORD" == "" ]; then
+                echo "Unable to retrieve Gaffer password from AWS SSM Parameter: ${PasswordParameter}"
+                exit 1
+              fi
 
-            # Copy graph schema into $GAFFER_CONF_DIR/schemas/
-            cd /tmp
+              # Decrypt the Accumulo password
+              PASSWORD=$(aws kms decrypt --region "${AWS::Region}" --ciphertext-blob fileb://<(echo "$ENCRYPTED_PASSWORD" | base64 -d) --query Plaintext --output text | base64 -d)
+              if [ "$PASSWORD" == "" ]; then
+                echo "Unable to decrypt Gaffer password!"
+                exit 2
+              fi
 
-            if [ "${GafferSchemaJarS3Url}" != "" ]; then
-              aws s3 cp "s3://${GafferSchemaJarS3Url}" schema.jar
-            elif [ "${GafferSchemaJarHttpUrl}" != "" ]; then
-              curl -fL -o schema.jar ${GafferSchemaJarHttpUrl}
-            fi
+              # Create Gaffer configuration
+              GAFFER_CONF_DIR=/opt/gaffer
 
-            if [ ! -f schema.jar ]; then
-              echo "Unable to retrieve schema jar!"
-              exit 3
-            fi
+              mkdir -p $GAFFER_CONF_DIR/etc
+              mkdir -p $GAFFER_CONF_DIR/schemas
 
-            jar -xf schema.jar schema/
-            mv schema/*.json $GAFFER_CONF_DIR/schemas/
+              tee -a $GAFFER_CONF_DIR/etc/graphConfig.json <<EOF
+              {
+                "graphId": "${GraphId}"
+              }
+              EOF
 
-            # Allow Tomcat to be reached on port 80
-            /sbin/iptables -A PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-port 8080
+              tee -a $GAFFER_CONF_DIR/etc/store.properties <<EOF
+              gaffer.store.class=uk.gov.gchq.gaffer.accumulostore.AccumuloStore
+              gaffer.store.properties.class=uk.gov.gchq.gaffer.accumulostore.AccumuloProperties
+              accumulo.instance=${AccumuloInstanceName}
+              accumulo.zookeepers=${GafferEmrMasterDNS}
+              accumulo.table=${GraphId}
+              accumulo.user=${UserName}
+              accumulo.password=$PASSWORD
+              EOF
 
-            /etc/init.d/tomcat7 start
+              # Point Tomcat at Gaffer config
+              tee -a /etc/tomcat7/tomcat7.conf <<EOF
+              CATALINA_OPTS="-Dgaffer.rest-api.basePath=rest \$CATALINA_OPTS"
+              CATALINA_OPTS="-Dgaffer.graph.config=$GAFFER_CONF_DIR/etc/graphConfig.json \$CATALINA_OPTS"
+              CATALINA_OPTS="-Dgaffer.schemas=$GAFFER_CONF_DIR/schemas \$CATALINA_OPTS"
+              CATALINA_OPTS="-Dgaffer.storeProperties=$GAFFER_CONF_DIR/etc/store.properties \$CATALINA_OPTS"
+              EOF
+
+              # Copy graph schema into $GAFFER_CONF_DIR/schemas/
+              cd /tmp
+
+              if [ "${GafferSchemaJarS3Url}" != "" ]; then
+                aws s3 cp "s3://${GafferSchemaJarS3Url}" schema.jar
+              elif [ "${GafferSchemaJarHttpUrl}" != "" ]; then
+                curl -fL -o schema.jar ${GafferSchemaJarHttpUrl}
+              fi
+
+              if [ ! -f schema.jar ]; then
+                echo "Unable to retrieve schema jar!"
+                exit 3
+              fi
+
+              jar -xf schema.jar schema/
+              mv schema/*.json $GAFFER_CONF_DIR/schemas/
+
+              # Allow Tomcat to be reached on port 80
+              /sbin/iptables -A PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-port 8080
+
+              /etc/init.d/tomcat7 start
+
+            - SchemaAccessDependency: !If [SchemaStoredInS3, !Ref WebServerS3SchemaAccessPolicy, ""]
+              MavenTarballAccessDependency: !If [BootstrapLocalMavenRepo, !Ref WebServerS3AccessMavenTarballPolicy, ""]
 
   WebServerSecurityGroup:
     Type: AWS::EC2::SecurityGroup
@@ -436,6 +439,21 @@ Resources:
         Statement:
           - Effect: Allow
             Resource: !Join ["", ["arn:aws:s3:::", Ref: GafferSchemaJarS3Url]]
+            Action:
+              - s3:GetObject
+
+  WebServerS3AccessMavenTarballPolicy:
+    Condition: BootstrapLocalMavenRepo
+    Type: AWS::IAM::Policy
+    Properties:
+      Roles:
+        - !Ref WebServerRole
+      PolicyName: !Join ["-", [Ref: "AWS::StackName", "mvn-tar-access"]]
+      PolicyDocument:
+        Version: 2012-10-17
+        Statement:
+          - Effect: Allow
+            Resource: !Join ["", ["arn:aws:s3:::", !Ref MavenRepoTarball]]
             Action:
               - s3:GetObject
 
